apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: warn
    logFormat: json
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "dump"
              reason: "ISFEventManager"
        - match:
            - receiver: "alert"
              reason: "ISFEventManager"
    receivers:
      - name: "dump"
        stdout: {}
      - name: "alert"
        webhook:
          endpoint: "https://hooks.slack.com/services/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"
          layout:
            text: "{{.Message}}"